### PR TITLE
Link changed to id

### PR DESCRIPTION
**Pull request by amanj752**
I changed the link of play game button in header to id of trick or treat section and it is working. Pls accept my pull request

### CODE REVIEW

**Comment by lukes-code** [comment]
Hello, someone has already completed this so I will not be merging it in to the code. I have added the hacktoberfest-accepted label to this however, so it should still count as a successful pull request towards hacktoberfest. Happy coding!

**Comment by amanj752** [comment]
Oh ok Thankyou for giving me this label can you suggest me some more issue like this if you know I want to solve issue.

**Comment by lukes-code** [comment]
Can you try to make the navbar responsive?

**Comment by amanj752** [comment]
yes sure I can do it

**Comment by amanj752** [comment]
can you create one issue for that so that i get one more label. And describe it in someline what you want in navbar.

**Comment by lukes-code** [comment]
Ive created the issue, please comment on the issue and I will assign it to you

**Comment by amanj752** [comment]
heyy can you add hactoberfest-accepted label because due to this lebel only my PR will count because still showing in pending pls add it.

**Comment by amanj752** [comment]
Some PR is still pending pls check it and provide me hactoberfest-accepted label some mistake in your label pls check

**Pull request closed without merging**
