### PR TITLE
Added Styling to Jokes Section

### PR DESCRIPTION
**Pull request by sheharyarIshfaq**

### CODE REVIEW

**Comment by sheharyarIshfaq** [comment]
Why it is closed? I have made changes as mentioned

**Comment by lukes-code** [comment]
Did not mean to close. Please check your code, the whole file is different, I will only accept changes to they spooky section. Thanks

**Comment by sheharyarIshfaq** [comment]
The whole code is changed because of the formatter.

**Comment by lukes-code** [comment]
> The whole code is changed because of the formatter.

Please remove the formatting

**Comment by sheharyarIshfaq** [comment]
ok

**Pull request closed without merging**
