### PR TITLE
final-contact-fix

### PR DESCRIPTION
**Pull request by GaushJ**

### CODE REVIEW

**Comment by GaushJ** [comment]
@lukes-code Please review the pull request

**Comment by lukes-code** [comment]
All you have done is remove the header again?

**Comment by GaushJ** [comment]
@lukes-code I did a stupid mistake of committing my changes to previously forked repository (previous issue) instead of pulling changes first which resulted in multiple merge conflicts .

**Comment by GaushJ** [comment]
@lukes-code I did not know about multiple pull request (about hacktoberfest ) as I am knew to this but this issue was my 4th and last pull request for completing hacktoberfest . 
cont
contrib

**Pull request closed without merging**
